### ISSUE TITLE
Traveling between dimensions causes a crash

### ISSUE THREAD

**Issue by Gegy** [Gegy/tic-tacs#11]
```
java.lang.IllegalStateException: No chunk holder after ticket has been added
	at net.minecraft.server.world.ServerChunkManager.getChunkFuture(ServerChunkManager.java:227)
	at net.minecraft.server.world.ServerChunkManager.getChunk(ServerChunkManager.java:140)
	at net.minecraft.world.World.getChunk(World.java:209)
	at net.minecraft.world.World.getBlockState(World.java:1726)
```

**Comment by Gegy** [comment]
This should be resolved in 0.1.1 :)
