### ISSUE TITLE
Log Spam regarding CompletableFuture

### ISSUE THREAD

**Issue by Desempregago** [Gegy/tic-tacs#20]
[14:42:31] [Server thread/ERROR]: Worker thread exited with unhandled exception
net.gegy1000.tictacs.chunk.ChunkNotLoadedException: null
	at net.gegy1000.tictacs.chunk.ChunkNotLoadedException.<clinit>(ChunkNotLoadedException.java:4) ~[tic-tacs-0.1.1.jar:?]
	at net.gegy1000.tictacs.chunk.entry.ChunkListener.get(ChunkListener.java:37) ~[tic-tacs-0.1.1.jar:?]
	at net.gegy1000.tictacs.chunk.entry.ChunkListener.get(ChunkListener.java:13) ~[tic-tacs-0.1.1.jar:?]
	at net.gegy1000.tictacs.chunk.SharedListener.poll(SharedListener.java:23) ~[tic-tacs-0.1.1.jar:?]
	at net.gegy1000.tictacs.chunk.future.AwaitAll.poll(AwaitAll.java:33) ~[tic-tacs-0.1.1.jar:?]
	at net.gegy1000.tictacs.chunk.future.AwaitAll.poll(AwaitAll.java:23) ~[tic-tacs-0.1.1.jar:?]
	at net.gegy1000.tictacs.chunk.future.AwaitAll.poll(AwaitAll.java:9) ~[tic-tacs-0.1.1.jar:?]
	at net.gegy1000.justnow.future.Handle.poll(Handle.java:19) ~[b83314b8-2b38-4e90-8f7f-406087c40325.jar:?]
	at net.gegy1000.tictacs.async.worker.ChunkTask.advance(ChunkTask.java:34) ~[tic-tacs-0.1.1.jar:?]
	at net.gegy1000.tictacs.async.worker.ChunkMainThreadExecutor.run(ChunkMainThreadExecutor.java:41) ~[tic-tacs-0.1.1.jar:?]
	at net.minecraft.class_1255.method_5386(class_1255.java:59) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764) ~[?:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_3215$class_4212.method_18859(class_3215.java:545) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_3215$class_4212.method_16075(class_3215.java:554) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_3215.method_19492(class_3215.java:280) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:749) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:737) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:103) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:721) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:674) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]

This happens every time a chunk gets generated.

**Comment by Justsnoopy30** [comment]
It also kills the worker thread every few seconds because of this, making this mod not work properly.

**Comment by Desempregago** [comment]
UPDATE: This seems to be tied to some specific mods. I'm not having this after trying to use less worldgen mods. But now I'm having a issue where chunks aren't getting saved... I lost my base 3 times in a row
