### ISSUE TITLE
Failed to generate chunk at ...

### ISSUE THREAD

**Issue by jukefr** [Gegy/tic-tacs#36]
I'm making this issue mainly to not clutter up #35 with this log but still document it somewhere but feel free to close this since it don't really have any steps to reproduce other than "i was running chunky and tictacs" and it does seem to be a rare occurence....

```
[14:31:31] [worldgen-worker-1/ERROR]: Failed to generate chunk at [-1602, 1602]
net.minecraft.class_148: Writing into PalettedContainer from multiple threads
	at net.minecraft.class_2794.method_12102(class_2794.java:228) ~[intermediary-server.jar:?]
	at net.gegy1000.tictacs.chunk.step.ChunkStep.addFeatures(ChunkStep.java:361) ~[tic-tacs-0.1.3.jar:?]
	at net.gegy1000.tictacs.chunk.step.ChunkStep.runUpgrade(ChunkStep.java:176) ~[tic-tacs-0.1.3.jar:?]
	at net.gegy1000.tictacs.chunk.upgrade.ChunkUpgrader.runStepTask(ChunkUpgrader.java:77) ~[tic-tacs-0.1.3.jar:?]
	at net.gegy1000.tictacs.chunk.upgrade.ChunkUpgradeStepper.upgradeChunk(ChunkUpgradeStepper.java:62) ~[tic-tacs-0.1.3.jar:?]
	at net.gegy1000.tictacs.chunk.upgrade.ChunkUpgradeStepper.lambda$openUpgradeTasks$2(ChunkUpgradeStepper.java:56) ~[tic-tacs-0.1.3.jar:?]
	at net.gegy1000.tictacs.chunk.upgrade.AcquireChunks.openUpgradeTasks(AcquireChunks.java:174) ~[tic-tacs-0.1.3.jar:?]
	at net.gegy1000.tictacs.chunk.upgrade.ChunkUpgradeStepper.openUpgradeTasks(ChunkUpgradeStepper.java:56) ~[tic-tacs-0.1.3.jar:?]
	at net.gegy1000.tictacs.chunk.upgrade.ChunkUpgradeStepper.pollStep(ChunkUpgradeStepper.java:49) ~[tic-tacs-0.1.3.jar:?]
	at net.gegy1000.tictacs.chunk.upgrade.ChunkUpgradeFuture.poll(ChunkUpgradeFuture.java:93) ~[tic-tacs-0.1.3.jar:?]
	at net.gegy1000.tictacs.chunk.upgrade.ChunkUpgradeFuture.poll(ChunkUpgradeFuture.java:16) ~[tic-tacs-0.1.3.jar:?]
	at net.gegy1000.tictacs.async.worker.ChunkTask.advance(ChunkTask.java:34) ~[tic-tacs-0.1.3.jar:?]
	at net.gegy1000.tictacs.async.worker.ChunkExecutor.run(ChunkExecutor.java:42) ~[tic-tacs-0.1.3.jar:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IllegalStateException
	at net.minecraft.class_2841.method_12334(class_2841.java:45) ~[intermediary-server.jar:?]
	at net.minecraft.class_2841.method_12328(class_2841.java:112) ~[intermediary-server.jar:?]
	at net.minecraft.class_2826.method_12256(class_2826.java:61) ~[intermediary-server.jar:?]
	at net.minecraft.class_2826.method_16675(class_2826.java:55) ~[intermediary-server.jar:?]
	at net.minecraft.class_2839.method_12010(class_2839.java:171) ~[intermediary-server.jar:?]
	at net.minecraft.class_3233.method_30092(class_3233.java:234) ~[intermediary-server.jar:?]
	at net.minecraft.class_1945.method_8652(class_1945.java:15) ~[intermediary-server.jar:?]
	at net.minecraft.class_3085.method_13471(class_3085.java:96) ~[intermediary-server.jar:?]
	at net.minecraft.class_3085.method_13151(class_3085.java:18) ~[intermediary-server.jar:?]
	at net.minecraft.class_2975.method_12862(class_2975.java:55) ~[intermediary-server.jar:?]
	at net.minecraft.class_2988.method_30384(class_2988.java:23) ~[intermediary-server.jar:?]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658) ~[?:?]
	at net.minecraft.class_2988.method_12892(class_2988.java:22) ~[intermediary-server.jar:?]
	at net.minecraft.class_2988.method_13151(class_2988.java:14) ~[intermediary-server.jar:?]
	at net.minecraft.class_2975.method_12862(class_2975.java:55) ~[intermediary-server.jar:?]
	at net.minecraft.class_1959.method_8702(class_1959.java:373) ~[intermediary-server.jar:?]
	at net.minecraft.class_2794.method_12102(class_2794.java:220) ~[intermediary-server.jar:?]
	... 13 more
```

**Comment by QPCrummer** [comment]
I have the same problem. It also sometimes says "failed to light chunk..."

**Comment by MagicSweet-dev** [comment]
Same issue 🤪
